FROM ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive
RUN apt update -y && apt-get install -y wget
RUN apt upgrade -y
# Try1
# RUN apt install -y gcc g++ gfortran cmake python python-dev python-numpy python-qt4 tk bison flex liblapack-dev libblas-dev libopenblas-dev zlib1g-dev
# RUN apt install -y libglu1 libharfbuzz-dev
# Try2
RUN apt-get -y install liblapacke-dev liblapacke liblapack3 liblapack-pic liblapack-dev libqt5opengl5-dev libqt5opengl5 libqt5concurrent5 libnlopt0 libqt5multimediawidgets5 build-essential flex cmake zlib1g-dev libopenmpi-dev openmpi-bin gnuplot libreadline-dev libncurses-dev libgmp-dev libmpfr-dev libmpc-dev qt4-dev-tools libqt4-dev libqt4-opengl-dev freeglut3-dev libqtwebkit-dev  libxt-dev
# Try3
# RUN apt -y install gcc g++ gfortran cmake python3 python3-dev python3-numpy tk bison flex liblapack-dev libopenblas-dev libboost-python-dev libboost-numpy-dev zlib1g-dev
# RUN apt -y install python-dateutil
#
RUN apt install -y x11-apps
#
ARG DOCKER_UID=1000
ARG DOCKER_USER=user
ARG DOCKER_PASSWORD=pass
RUN useradd -m --uid ${DOCKER_UID} --groups root ${DOCKER_USER} \
  && echo ${DOCKER_USER}:${DOCKER_PASSWORD} | chpasswd
COPY salome_meca-2019.0.3-1-universal.tgz /tmp/
RUN tar zxvf /tmp/salome_meca-2019.0.3-1-universal.tgz -C /tmp/
RUN rm -rf /tmp/salome_meca-2019.0.3-1-universal.tgz /tmp/salome_meca-2019.0.3-1-universal.run
RUN /tmp/salome_meca-2019.0.3-1-universal.run -f -q -t /home/${DOCKER_USER}/salome_meca -l English
USER ${DOCKER_USER}
WORKDIR /home/${DOCKER_USER}