FROM ubuntu:18.04
RUN apt update -y
RUN apt upgrade -y
# Install GFortran 
RUN apt install -y gfortran
# Install MKL
RUN apt install -y wget
RUN cd /tmp
RUN apt install -y gnupg
RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
RUN apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
RUN wget https://apt.repos.intel.com/setup/intelproducts.list -O /etc/apt/sources.list.d/intelproducts.list
RUN apt update -y
RUN apt install -y intel-mkl-2019.0-045
# Install code
RUN apt install -y curl
#
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
RUN install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
RUN apt install -y apt-transport-https
RUN apt update
RUN apt install -y code
# Install others
RUN apt install -y x11-apps
RUN apt install -y libx11-xcb-dev
RUN apt install -y libasound2
# Wget extension
ARG publisher=krvajalm
ARG extensionname=linter-gfortran
ARG version=2.1.1
RUN wget https://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${extensionname}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage -P /tmp
RUN mv /tmp/Microsoft.VisualStudio.Services.VSIXPackage /tmp/krvajalm.linter-gfortran
ARG publisher=hansec
ARG extensionname=fortran-ls
ARG version=0.6.0
RUN wget https://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${extensionname}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage -P /tmp
RUN mv /tmp/Microsoft.VisualStudio.Services.VSIXPackage /tmp/hansec.fortran-ls
ARG publisher=ekibun
ARG extensionname=fortranbreaker
ARG version=0.0.4
RUN wget https://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${extensionname}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage -P /tmp
RUN mv /tmp/Microsoft.VisualStudio.Services.VSIXPackage /tmp/ekibun.fortranbreaker
# Create User
ARG DOCKER_UID=1000
ARG DOCKER_USER=user
ARG DOCKER_PASSWORD=pass
RUN useradd -m --uid ${DOCKER_UID} --groups root ${DOCKER_USER} \
  && echo ${DOCKER_USER}:${DOCKER_PASSWORD} | chpasswd
USER ${DOCKER_USER}
# Install extension
WORKDIR /tmp
# RUN code --force --install-extension krvajalm.linter-gfortran
# RUN code --force --install-extension hansec.fortran-ls
# RUN code --force --install-extension ekibun.fortranbreaker
# # Set starting directory
# WORKDIR /mnt/windows/