version: '3'

services:
    myopenfoam:
        build: .
        container_name: myopenfoam
        volumes: 
            - C:/Users:/mnt/windows
        environment: 
            DISPLAY: 192.168.56.1:0.0